#!/bin/sh
export ORG=org1
export DOMAIN=example.com
export DOCKER_NETWORK=test_net

export SERVICE_BIND_PORT=8000
#
export IDENTITY_SERVICE_HOST=identity.service.${ORG}.${DOMAIN}
export IDENTITY_SERVICE_BIND_PORT=7000
#
export PROCESS_MANAGEMENT_HOST=process.management.service.${ORG}.${DOMAIN}
export PROCESS_MANAGEMENT_BIND_PORT=7100
#
export ADMINISTRATION_SERVICE_HOST=administration.service.${ORG}.${DOMAIN}
export ADMINISTRATION_SERVICE_BIND_PORT=7200
#
export SERVICE_HOST=service.${ORG}.${DOMAIN}
