#!/bin/sh
export ORG=org3
export DOMAIN=example.com
export DOCKER_NETWORK=test_net

export SERVICE_BIND_PORT=8002
#
export IDENTITY_SERVICE_HOST=identity.service.${ORG}.${DOMAIN}
export IDENTITY_SERVICE_BIND_PORT=7002
#
export PROCESS_MANAGEMENT_HOST=process.management.service.${ORG}.${DOMAIN}
export PROCESS_MANAGEMENT_BIND_PORT=7102
#
export ADMINISTRATION_SERVICE_HOST=administration.service.${ORG}.${DOMAIN}
export ADMINISTRATION_SERVICE_BIND_PORT=7202
#
export MAINTENANCE_SERVICE_HOST=maintenance.service.${ORG}.${DOMAIN}
export MAINTENANCE_SERVICE_BIND_PORT=7302
#
export SERVICE_HOST=service.${ORG}.${DOMAIN}
